### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by o-felixz** [fumiyas/python-nkf#5]
Like the title says - will nkf be updated with python 3 support? :slightly_smiling_face:

**Comment by fumiyas** [comment]
FYI.

スレッド 公開討議:Pythonモジュールの問題と将来 - nkf Network Kanji Filter - OSDN
https://ja.osdn.net/projects/nkf/forums/1007/42359/

**Comment by nburlett** [comment]
Is there a test suite for nkf? I did a very fast port to python3 but I have little to test it on. I'm using it to decode some files that claim to be encoded with iso-2022-jp but use the NEC special characters extension from  JIS_X_0208, which Python doesn't decode properly. My port correctly decodes the regression test I have in my test suite containing `b'\x1b$B-!\x1b(B'` but that's all I have at the moment.

**Comment by taizo** [comment]
Hello.
Is there any plan to release a new version "0.3.0?" in the near future? I'd like to have [this fix](https://github.com/fumiyas/python-nkf/blame/master/nkf.c#L16-L18) that was done last year for supporting python 3.11.
I confirmed nkf==0.2.0 works on python<=3.9.18 but the error of `SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats` happens on both 3.10 and 3.11.

こんにちは。nkfモジュールの開発・メンテナンスありがとうございます。
Python 3.11以降のバージョンで利用したいため、[こちらの修正](https://github.com/fumiyas/python-nkf/blame/master/nkf.c#L16-L18)が入った新しいバージョンをリリースする予定はありますでしょうか？
また、動作確認等でお手伝いできたらと思います。
ちなみに手元の環境(nkf==0.2.0を利用)では、3.9.18までは動作することは確認しております。(3.9系はDeprecationの警告表示)
3.10, 3.11 では、`SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats` となりサポートされていないようです。

Thank you.
